"""empty message

Revision ID: 0f377aca3e8f
Revises: 6c31f0dfc16a
Create Date: 2025-09-08 19:28:44.943550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f377aca3e8f'
down_revision = '6c31f0dfc16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
