"""initial migration

Revision ID: 321ca4474540
Revises: 
Create Date: 2025-10-17 13:38:47.521431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321ca4474540'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('subtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('subtype_id', sa.Integer(), nullable=False),
    sa.Column('numero_registro_general', sa.String(length=120), nullable=True),
    sa.Column('articulo', sa.String(length=120), nullable=True),
    sa.Column('nombre_local_tradicional', sa.String(length=120), nullable=True),
    sa.Column('referencia_topografica', sa.String(length=120), nullable=True),
    sa.Column('numero_piezas', sa.Integer(), nullable=True),
    sa.Column('fecha_origen', sa.String(length=120), nullable=True),
    sa.Column('fecha_adquisicion', sa.String(length=120), nullable=True),
    sa.Column('procedencia', sa.String(length=120), nullable=True),
    sa.Column('autor', sa.String(length=120), nullable=True),
    sa.Column('aportado_por', sa.String(length=120), nullable=True),
    sa.Column('propietario', sa.String(length=120), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=True),
    sa.Column('valoracion_actual', sa.Float(), nullable=True),
    sa.Column('materiales', sa.String(length=255), nullable=True),
    sa.Column('medidas', sa.String(length=120), nullable=True),
    sa.Column('estado_general', sa.String(length=120), nullable=True),
    sa.Column('restauraciones', sa.String(length=255), nullable=True),
    sa.Column('uso_funcion', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('exposiciones', sa.String(length=255), nullable=True),
    sa.Column('referencias_bibliograficas', sa.String(length=255), nullable=True),
    sa.Column('prestamos', sa.String(length=255), nullable=True),
    sa.Column('image1', sa.String(length=255), nullable=True),
    sa.Column('image2', sa.String(length=255), nullable=True),
    sa.Column('image3', sa.String(length=255), nullable=True),
    sa.Column('image4', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['subtype_id'], ['subtype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('subtype')
    op.drop_table('type')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
