"""empty message

Revision ID: 34044410b02b
Revises: f818b509c61d
Create Date: 2025-09-01 20:04:44.990596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34044410b02b'
down_revision = 'f818b509c61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
