"""empty message

Revision ID: 6c31f0dfc16a
Revises: cefe3260c3ae
Create Date: 2025-09-08 19:13:34.433022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c31f0dfc16a'
down_revision = 'cefe3260c3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
