"""empty message

Revision ID: 892703de6766
Revises: 2d6be988aaf3
Create Date: 2025-09-08 19:07:59.589032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892703de6766'
down_revision = '2d6be988aaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=255), nullable=True))
        batch_op.drop_column('foto')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
