"""empty message

Revision ID: 99918e68f34e
Revises: d703faeb0913
Create Date: 2025-09-01 18:37:15.177720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99918e68f34e'
down_revision = 'd703faeb0913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=120), nullable=False))
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['usuario'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'])
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
