"""empty message

Revision ID: d7a19827f1d5
Revises: e121627ae169
Create Date: 2025-09-01 20:41:09.413330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a19827f1d5'
down_revision = 'e121627ae169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero_registro_general', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('articulo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nombre_local_tradicional', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('referencia_topografica', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('numero_piezas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_origen', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('fecha_adquisicion', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('procedencia', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('autor', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('aportado_por', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('propietario', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('precio_compra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valoracion_actual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('materiales', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('medidas', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('estado_general', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('restauraciones', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('uso_funcion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('exposiciones', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('referencias_bibliograficas', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prestamos', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('foto')
        batch_op.drop_column('prestamos')
        batch_op.drop_column('referencias_bibliograficas')
        batch_op.drop_column('exposiciones')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('uso_funcion')
        batch_op.drop_column('restauraciones')
        batch_op.drop_column('estado_general')
        batch_op.drop_column('medidas')
        batch_op.drop_column('materiales')
        batch_op.drop_column('valoracion_actual')
        batch_op.drop_column('precio_compra')
        batch_op.drop_column('propietario')
        batch_op.drop_column('aportado_por')
        batch_op.drop_column('autor')
        batch_op.drop_column('procedencia')
        batch_op.drop_column('fecha_adquisicion')
        batch_op.drop_column('fecha_origen')
        batch_op.drop_column('numero_piezas')
        batch_op.drop_column('referencia_topografica')
        batch_op.drop_column('nombre_local_tradicional')
        batch_op.drop_column('articulo')
        batch_op.drop_column('numero_registro_general')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
